src/main/java/br/edu/utfpr/recominer/model/matrix/EntityMatrix.java
package br.edu.utfpr.recominer.model.matrix;

import br.edu.utfpr.recominer.model.InterfaceEntity;
import br.edu.utfpr.recominer.model.Startable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OrderColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author douglas
 */
@Entity
@Table(name = "matrix")
@NamedQueries({
    @NamedQuery(name = "Matrix.findAllTheLatest", query = "SELECT m FROM EntityMatrix m ORDER BY m.id DESC")
})
public class EntityMatrix implements InterfaceEntity, Startable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date started;
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date stoped;
    private boolean complete;
    @Lob
    @Basic(fetch = FetchType.LAZY)
    private String log;
    private Map<Object, Object> params;
    private String classServicesName;
    private String repository;
    @OrderColumn(name = "index")
    @OneToMany(mappedBy = "matrix", orphanRemoval = true, cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<EntityMatrixNode> nodes;
    @Transient
    private String additionalFilename;

    public EntityMatrix() {
        started = new Date();
        complete = false;
        nodes = new ArrayList<>();
        params = new HashMap<>();
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public boolean isComplete() {
        return complete;
    }

    public void setComplete(boolean complete) {
        this.complete = complete;
    }

    public Date getStarted() {
        return started;
    }

    public void setStarted(Date started) {
        this.started = started;
    }

    public Date getStoped() {
        return stoped;
    }

    public void setStoped(Date stoped) {
        this.stoped = stoped;
    }

    public Map<Object, Object> getParams() {
        return params;
    }

    @Override
    public String getLog() {
        return log;
    }

    @Override
    public void setLog(String log) {
        this.log = log;
    }

    public List<EntityMatrixNode> getNodes() {
        return nodes;
    }

    public void setNodes(List<EntityMatrixNode> nodes) {
        this.nodes = nodes;
    }

    public String getClassServicesName() {
        return classServicesName;
    }

    public String getClassServicesSingleName() {
        if (classServicesName != null) {
            String[] tokens = classServicesName.split("\\.");
            if (tokens.length > 0) {
                return tokens[tokens.length - 1];
            }
        }
        return classServicesName;
    }

    public void setClassServicesName(String classServices) {
        this.classServicesName = classServices;
    }

    public String getAdditionalFilename() {
        return additionalFilename;
    }

    public void setAdditionalFilename(String additionalFilename) {
        this.additionalFilename = additionalFilename;
    }

    public String getRepository() {
        return repository;
    }

    public void setRepository(String repository) {
        this.repository = repository;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof EntityMatrix)) {
            return false;
        }
        EntityMatrix other = (EntityMatrix) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        final Object filename = params.get("filename");
        if (filename != null) {
            final Object additionalFilename = params.get("additionalFilename");
            if (additionalFilename != null) {
                return StringUtils.capitalize(repository) + " " + filename + additionalFilename;
            }
            return StringUtils.capitalize(repository) + " " + filename;
        } else {
            return "(" + id + ") " + repository + " - " + getClassServicesSingleName();
        }
    }

    @Override
    public String getDownloadFileName() {
        final Object filename = params.get("filename");
        if (filename != null) {

            final Object additionalFilename = params.get("additionalFilename");
            if (additionalFilename != null) {
                return StringUtils.capitalize(repository) + " " + filename + additionalFilename;
            }
            return StringUtils.capitalize(repository) + " " + filename;
        } else {
            return this.repository + "-" + this.started;
        }
    }

    public void addAllParams(Map<Object, Object> params) {
        this.params.putAll(params);
    }

}

src/main/java/br/edu/utfpr/recominer/model/matrix/EntityMatrixNode.java
package br.edu.utfpr.recominer.model.matrix;

import br.edu.utfpr.recominer.model.EntityNode;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 *
 * @author douglas
 */
@Entity
@Table(name = "matrix_node", indexes = {
    @Index(columnList = "matrix_id")
})
@DiscriminatorValue(value = "EntityMatrixNode")
public class EntityMatrixNode extends EntityNode {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "matrix_id", referencedColumnName = "id")
    private EntityMatrix matrix;

    public EntityMatrixNode() {
        super();
    }

    public EntityMatrixNode(String line) {
        super(line);
    }

    public EntityMatrix getMatrix() {
        return matrix;
    }

    public void setMatrix(EntityMatrix matrix) {
        this.matrix = matrix;
    }
}

src/main/webapp/pages/matrix/bichoCreateQueue.xhtml
<div xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
     xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui"
     xmlns:ui="http://java.sun.com/jsf/facelets" 
     xmlns:c="http://java.sun.com/jsp/jstl/core">

    <p:fieldset legend="Matrix generation">
        <h:form prependId="false" id="formMatrixQueue" >
            <p:growl globalOnly="true" id="messages" />

            <b><h:outputText value="Select a Repository: " /></b>  
            <p:selectOneListbox  id="repositories" style="width: 100%;min-height:100px" value="#{bichoMatrixQueueBean.repositoryId}"  >
                <f:selectItems value="#{bichoMinerRepositoryBean.allRepositories}" var="repo" itemLabel="#{repo} (issues / vcs)" itemDescription="#{repo}" itemValue="#{repo}" />
                <p:ajax event="change" process="@this" />
            </p:selectOneListbox>

            <br />

            <b><h:outputText value="Select a Matrix Service Class: " /></b>  
            <p:selectOneListbox id="serviceClass" style="width: 100%;min-height:100px" converter="#{bichoMatrixQueueBean.converterClass}" value="#{bichoMatrixQueueBean.serviceClass}" >
                <f:selectItems value="#{bichoMatrixQueueBean.servicesClasses}" var="serviceClass" itemLabel="#{serviceClass.simpleName}" itemDescription="#{serviceClass.name}" itemValue="#{serviceClass}" />
                <p:ajax event="change" process="@this" update="matrixFilter" />
            </p:selectOneListbox>

            <br />
            <br />
            <h:panelGroup id="matrixFilter">
                <c:if test="#{bichoMatrixQueueBean.serviceClass != null}" >
                    <p:panel header="Filters for #{bichoMatrixQueueBean.serviceClass.simpleName}:" >
                        <ui:include src="./filter/#{bichoMatrixQueueBean.serviceClass.simpleName}.xhtml">
                            <ui:param name="bean" value="#{bichoMatrixQueueBean}" />
                        </ui:include>
                    </p:panel>
                </c:if>
            </h:panelGroup>
            <br />
            <br />

            <p:commandButton widgetVar="queueButtonVar" actionListener="#{bichoMatrixQueueBean.queue()}" value="Queue"
                             update="logTextArea" />

            <p:commandButton widgetVar="queueAllProjectsButtonVar" actionListener="#{bichoMatrixQueueBean.queueAllProjects()}" value="Queue All Projects"
                             update="logTextArea" />

            <p:commandButton widgetVar="queueAllVersionsButtonVar" actionListener="#{bichoMatrixQueueBean.queueAllVersions()}" value="Queue All"
                             update="logTextArea" />

            <p:commandButton widgetVar="showQueueButtonVar" actionListener="#{bichoMatrixQueueBean.showQueue()}" value="Show Queue"
                             update="logTextArea" />

            <p:commandButton widgetVar="removeLastFromQueueButtonVar" actionListener="#{bichoMatrixQueueBean.removeLastFromQueue()}" value="Remove Last"
                             update="logTextArea" />

            <p:commandButton widgetVar="removeLastFromQueueButtonVar" actionListener="#{bichoMatrixQueueBean.removeFirstFromQueue()}" value="Remove First"
                             update="logTextArea" />

            <p:commandButton widgetVar="clearQueueButtonVar" actionListener="#{bichoMatrixQueueBean.clearQueue()}" value="Clear Queue"
                             update="logTextArea" />

            <p:commandButton widgetVar="startQueueButtonVar" actionListener="#{bichoMatrixQueueBean.startQueue()}" value="Start Queue"
                             onclick="startButtonVar.disable();progressVar.start();textAreaUpdaterVar.start();" update="loadingImage,logTextArea" />

            <br />
            <br />

            <p:progressBar id="progress" widgetVar="progressVar" ajax="true" value="#{bichoMatrixQueueBean.progress}" labelTemplate="{value}%" styleClass="animated" interval="3000" >
                <p:ajax event="complete" listener="#{bichoMatrixQueueBean.onComplete()}" update="messages,loadingImage,logTextArea" oncomplete="startButtonVar.enable();textAreaUpdaterVar.stop();"/>
            </p:progressBar>

            <br />
            <div style="margin: auto;text-align: center">
                <p:outputPanel  id="loadingImage"  >
                    <p:graphicImage alt="Loading..." width="50" url="resources/images/loading.gif" rendered="#{bichoMatrixQueueBean.initialized}" />
                </p:outputPanel>
            </div>
            <br />

            <p:poll id="textAreaUpdater" widgetVar="textAreaUpdaterVar" async="true" interval="4" 
                    update="logTextArea,loadingImage,progress"
                    stop="#{!bichoMatrixQueueBean.initialized}"
                    autoStart="#{bichoMatrixQueueBean.initialized}" />

            <h3>Log:</h3>
            <br />
            <p:inputTextarea value="#{bichoMatrixQueueBean.log}" id="logTextArea" style="width: 100%" rows="30" autoResize="autoResize" readonly="true" />

        </h:form>
    </p:fieldset>
</div>

src/main/webapp/pages/matrix/view.xhtml
<div xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
     xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui">

    <h:form>
        <h:outputText value="#{bichoMatrixViewBean.reloadList()}" />
    </h:form>

    <p:fieldset legend="Matrices generated">
        <h:form prependId="false" >
            <p:growl globalOnly="true" id="messages" />
            <p:commandButton onclick="PrimeFaces.monitorDownload(start, stop)" ajax="false" value="Download all CSV">
                <p:fileDownload value="#{bichoMatrixViewBean.downloadAllCSV()}" />
            </p:commandButton>
            <p:commandButton type="button" icon="ui-icon-trash" value="Delete All"
                             id="deleteAllMatrices" onclick="PF('confirmationDeleteAll').show()" />
            <p:dataTable var="matrix" value="#{bichoMatrixViewBean.matrices}" id="list" rows="10" lazy="false"
                         emptyMessage="No matrices generated found." paginator="true" paginatorPosition="bottom"
                         paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="10,25,50,100" >
                <p:column headerText="ID">
                    <h:outputText value="#{matrix.id}" />
                </p:column>

                <p:column headerText="Repository">
                    <h:outputText value="#{matrix.repository}" />
                </p:column>

                <p:column headerText="Matrix">
                    <h:outputText value="#{matrix.toString()}" />
                </p:column>

                <p:column headerText="Class Service">
                    <h:outputText value="#{matrix.classServicesSingleName}" />
                </p:column>

                <p:column headerText="Started" >
                    <h:outputText value="#{matrix.started}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                </p:column>

                <p:column headerText="Stoped" >
                    <h:outputText value="#{matrix.stoped}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                </p:column>

                <p:column headerText="Completed">
                    <h:outputText value="#{matrix.complete}" />
                </p:column>

                <p:column headerText="Download Files">
                    <p:commandButton action="#{bichoMatrixViewBean.downloadLOG(matrix)}" ajax="false" value="Log"/>
                    <p:commandButton action="#{bichoMatrixViewBean.downloadCSV(matrix)}" ajax="false" value="CSV" title="#{matrix.toString()}"/>
                    <p:commandButton action="#{bichoMatrixViewBean.downloadAllCSVOfOneVersion(matrix.toString())}" ajax="false" value="All CSV" title="#{matrix}"/>
                    <p:commandButton action="#{bichoMatrixViewBean.downloadParams(matrix)}"  ajax="false" value="Params"/>
                </p:column>

                <p:column headerText="Options">
                    <p:commandButton  icon="ui-icon-trash" title="Delete this Matrix" actionListener="#{bichoMatrixViewBean.addMatrixForDeleteInSession(matrix)}"
                                      id="matrixDelete" oncomplete="PF('confirmation').show()" />
                </p:column>
            </p:dataTable>

            <p:confirmDialog  id="confirmDelete" widgetVar="confirmation"
                              message="Really delete this matrix?" header="Confirmation"
                              severity="alert">
                <p:commandButton value="Yes" id="confirmYes" update="list messages" oncomplete="PF('confirmation').hide()" style="position: relative;left: 80px"
                                 actionListener="#{bichoMatrixViewBean.deleteMatrixInSession()}">
                </p:commandButton>
                <p:commandButton value="No" id="confirmNo" oncomplete="PF('confirmation').hide()" style="position: relative;left: 80px"
                                 actionListener="#{bichoMatrixViewBean.removeMatrixFromSession()}"/>
            </p:confirmDialog>

            <p:confirmDialog  id="confirmDeleteAll" widgetVar="confirmationDeleteAll"
                              message="Really delete all matrices?" header="Confirmation"
                              severity="alert">
                <p:commandButton value="Yes" update="list messages" oncomplete="PF('confirmationDeleteAll').hide()" style="position: relative;left: 80px"
                                 actionListener="#{bichoMatrixViewBean.deleteAll()}"/>
                <p:commandButton value="No" oncomplete="PF('confirmationDeleteAll').hide()" style="position: relative;left: 80px" />
            </p:confirmDialog>
        </h:form>
    </p:fieldset>
</div>